In [30]:
import numpy as np
import sympy as sp


In [ ]:
# Create matrix A
A = np.array([[2],
              [3],
              [4]])

# Create matrix B
B = np.array([[5],
              [6],
              [-7]])

# Create matrix C
C = np.array([[7, 8, -9]])

# Print the matrices
print("Column Matrix A:")
print(A)
print("\nColumn Matrix B:")
print(B)
print("\nRow Matrix C:")
print(C)

In [ ]:
# 1.1 Find A*B and B*C'

A = sp.Matrix([[2],
                [3],
                [4]])

B = sp.Matrix([[5],
                [6],
                [-7]])

C = sp.Matrix([[7, -8, -9]])

sp.pprint("A · B (dot product):")
sp.pprint(np.dot(A.T, B))  # or A.T @ B

sp.pprint("\nB · C.T (dot product):")
sp.pprint(np.dot(B.T, C.T))  # B is (3,1), C.T is (3,1) → use B.T @ C.T
# Alternatively: np.dot(B.flatten(), C.flatten())

A · B (dot product):
[[0]]
                      
B · C.T (dot product):
[[50]]


In [56]:
# 1.2 Show that A + B = B + A
A = sp.Matrix([[0, 1],
                [2, 3]])
B = sp.Matrix([[4, 5],
                [6, -7]])

print("\nA + B:")
sp.pprint(A + B)    
print("\nB + A:")
sp.pprint(B + A)    

print("\nA + B == B + A")
sp.pprint(A + B == B + A)


A + B:
⎡4  6 ⎤
⎢     ⎥
⎣8  -4⎦

B + A:
⎡4  6 ⎤
⎢     ⎥
⎣8  -4⎦

A + B == B + A
True


In [29]:
# 1.3 Find 3A - 0.5B from # 1.2
sp.pprint(3 * A - 0.5 * B)

⎡-2.0  0.5 ⎤
⎢          ⎥
⎣3.0   12.5⎦


In [34]:
# 1.4 Find AB and BA for matrices from # 1.2
print("\nAB:")
sp.pprint(A @ B)
print("\nBA:")
sp.pprint(B @ A)


AB:
⎡6   -7 ⎤
⎢       ⎥
⎣26  -11⎦

BA:
⎡10   19 ⎤
⎢        ⎥
⎣-14  -15⎦


In [36]:
# 1.5 Find AB and BA for matrices below

# Define matrices with incompatible dimensions for multiplication
A = sp.Matrix([[1, 2, 3],  # 2x3
                [4, 5, 6]])

B = sp.Matrix([[7, 8],     # 2x2
              [9, 10]])

sp.pprint("Matrix A shape:", A.shape)
sp.pprint("Matrix B shape:", B.shape)

try:
    # Attempt matrix multiplication
    result = A @ B
    sp.pprint("A @ B =")
    sp.pprint(result)
except ValueError as e:
    sp.pprint(f"Error during matrix multiplication: {e}")
    sp.pprint("Reason: Number of columns in A (3) does not match number of rows in B (2)")

# Another example: Addition with incompatible shapes
C = sp.Matrix([[1, 2],     # 2x2
                [3, 4]])

D = sp.Matrix([[5, 6, 7]]) # 1x3

sp.pprint("\nMatrix C shape:", C.shape)
sp.pprint("Matrix D shape:", D.shape)

try:
    # Attempt matrix addition
    result = C + D
    print("C + D =")
    sp.pprint(result)
except ValueError as e:
    print(f"Error during matrix addition: {e}")
    print("Reason: Shapes (2,2) and (1,3) are not compatible for addition")

TypeError: pretty_print() takes 1 positional argument but 2 were given

In [57]:
# 1.6 Verify that (BA)' = A'B' for matrices below
A = sp.Matrix([[1, 2, 3],  # 2x3
              [4, 5, 6]])

B = sp.Matrix([[7, 8],     # 2x2
                [9, 10]])

# Compute (BA)' and A'B'
lhs = (B @ A).T
rhs = A.T @ B.T

print("Left-hand side (BA)' =")
sp.pprint(lhs)
print("\nRight-hand side A'B' =")
sp.pprint(rhs)

# Check if they are equal

if lhs.equals(rhs):
    print("\nVerification successful: (BA)' = A'B'")
else:
    print("\nVerification failed: (BA)' ≠ A'B'")  

Left-hand side (BA)' =
⎡39  49⎤
⎢      ⎥
⎢54  68⎥
⎢      ⎥
⎣69  87⎦

Right-hand side A'B' =
⎡39  49⎤
⎢      ⎥
⎢54  68⎥
⎢      ⎥
⎣69  87⎦

Verification successful: (BA)' = A'B'


In [44]:
# 1.7 Find AB and AC if
A = sp.Matrix([[4, 2, 0],
                [2, 1, 0],
                [-2, -1, 1]])
B = sp.Matrix([[2, 3, 1],
                [2, -2, -2],
                [-1, 2, 1]])
C = sp.Matrix([[3, 1, -3],
                [0, 2, 6],
                [-1, 2, 1]])
print("A*B:")
sp.pprint(A @ B)
print("\nA*C:")
sp.pprint(A @ C)

A*B:
⎡12  8   0⎤
⎢         ⎥
⎢6   4   0⎥
⎢         ⎥
⎣-7  -2  1⎦

A*C:
⎡12  8   0⎤
⎢         ⎥
⎢6   4   0⎥
⎢         ⎥
⎣-7  -2  1⎦


In [58]:
# 1.9 Find AB and A - B for matrices below
# Define 2×2 symbolic matrices
C = sp.Matrix([[1, 2],
               [3, 4]])
D = sp.Matrix([[0, 0],
               [0, 0]])
E = sp.Matrix([[5, 6],
               [7, 8]])
F = sp.Matrix([[-1, 0],
               [2, 1]])
G = sp.Matrix([[-2, -3],
               [1, 1]])

# Construct block matrices A and B
A = sp.BlockMatrix([[C, D],
                    [E, C]])
B = sp.BlockMatrix([[F, G],
                    [F, E]])

# Convert to full matrices
A_full = A.as_explicit()
B_full = B.as_explicit()

# Compute AB and A - B
AB = A_full * B_full
A_minus_B = A_full - B_full

# Display results
print("AB:")
sp.pprint(AB)

print("\nA - B:")
sp.pprint(A_minus_B)

AB:
⎡3   2   0   -1⎤
⎢              ⎥
⎢5   4   -2  -5⎥
⎢              ⎥
⎢10  8   15  13⎥
⎢              ⎥
⎣14  12  37  37⎦

A - B:
⎡2  2  2   3 ⎤
⎢            ⎥
⎢1  3  -1  -1⎥
⎢            ⎥
⎢6  6  -4  -4⎥
⎢            ⎥
⎣5  7  -4  -4⎦


In [ ]:
# 1.9 with NumPy

# Define 2×2 blocks
C = np.array([[1, 2],
              [3, 4]])
D = np.array([[0, 0],
              [0, 0]])
E = np.array([[5, 6],
              [7, 8]])
F = np.array([[-1, 0],
              [2, 1]])
G = np.array([[-2, -3],
              [1, 1]])

# Construct full 4×4 block matrices
A = np.block([[C, D],
              [E, C]])
B = np.block([[F, G],
              [F, E]])

# Compute AB and A - B
AB = A @ B
A_minus_B = A - B

# Display results
print("AB:")
print(AB)

print("\nA - B:")
print(A_minus_B)

AB:
[[ 3  2  0 -1]
 [ 5  4 -2 -5]
 [10  8 15 13]
 [14 12 37 37]]

A - B:
[[ 2  2  2  3]
 [ 1  3 -1 -1]
 [ 6  6 -4 -4]
 [ 5  7 -4 -4]]


In [86]:
# 1.11 Matrices for row echelon form (REF) examples
A = sp.Matrix([[1, 2, -1, 0],
                [0, 0, 1, 4],
                [0, 0, 0, 0]])
B = sp.Matrix([[0, 1, 4],
                [1, 2, 3]])
C = sp.Matrix([[0, 2, 4],
                [0, 0, 1]])
D = sp.Matrix([[0, 1, 0, 4],
                [0, 0, 1, 3],
                [0, 0, 0, 1]])
E = sp.Matrix([[1, 2, 3],
                [4, 9, 7]])


In [95]:
# Option with only REF from SymPy
def to_ref_sympy(M):
    M = M.copy()
    rows, cols = M.shape
    lead = 0
    for r in range(rows):
        if lead >= cols:
            break
        # Find pivot
        i = r
        while M[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if lead == cols:
                    return M
        # Swap
        M.row_swap(r, i)
        # Eliminate below
        for i in range(r + 1, rows):
            if M[i, lead] != 0:
                factor = M[i, lead] / M[r, lead]
                M.row_op(i, lambda v, j: v - factor * M[r, j])
        lead += 1
    return M

# Apply
ref_manual = to_ref_sympy(E)

print("True Row Echelon Form (REF only):")
sp.pprint(ref_manual)

True Row Echelon Form (REF only):
⎡1  2  3 ⎤
⎢        ⎥
⎣0  1  -5⎦


In [96]:
# 1.12 Transform B,C and E to REF using SymPy
# Option with RREF from SymPy
# Reduced Row Echelon Form (RREF)
def to_row_echelon_form_sympy(mat, show_steps=False):
    """Convert matrix to Row Echelon Form using SymPy (exact arithmetic)"""
    print("Original Matrix:")
    pprint(E)

    ref_E, pivots = E.rref()

    print("\nRow Echelon Form:")
    pprint(ref_E)
    print("\nPivot columns:", pivots)

    return ref_E, pivots

# Example usage:
#M = Matrix([[1, 2, 3], [0, 0, 1], [0, 0, 0]])
to_row_echelon_form_sympy(E, show_steps=True)

Original Matrix:
⎡1  2  3⎤
⎢       ⎥
⎣4  9  7⎦

Row Echelon Form:
⎡1  0  13⎤
⎢        ⎥
⎣0  1  -5⎦

Pivot columns: (0, 1)


(Matrix([
 [1, 0, 13],
 [0, 1, -5]]),
 (0, 1))

In [111]:
# 1.13 Transform matrices to RREF with sympy
N = sp.Matrix([[1, 2, -1, 6],
                 [3, 8, 9, 10],
                 [2, -1, 2, -2]])

# Reduced Row Echelon Form (RREF)
def to_row_echelon_form_sympy(mat, show_steps=False):
    """Convert matrix to Row Echelon Form using SymPy (exact arithmetic)"""
    print("Original Matrix:")
    pprint(N)

    ref_N, pivots = N.rref()

    print("\nRow Echelon Form (RREF):")
    pprint(ref_N)
    print("\nPivot columns:", pivots)

    return ref_N, pivots


to_row_echelon_form_sympy(N, show_steps=True)

Original Matrix:
⎡1  2   -1  6 ⎤
⎢             ⎥
⎢3  8   9   10⎥
⎢             ⎥
⎣2  -1  2   -2⎦

Row Echelon Form (RREF):
⎡1  0  0  1 ⎤
⎢           ⎥
⎢0  1  0  2 ⎥
⎢           ⎥
⎣0  0  1  -1⎦

Pivot columns: (0, 1, 2)


(Matrix([
 [1, 0, 0,  1],
 [0, 1, 0,  2],
 [0, 0, 1, -1]]),
 (0, 1, 2))

In [98]:
# Option with only REF from SymPy
def to_ref_sympy(M):
    M = M.copy()
    rows, cols = M.shape
    lead = 0
    for r in range(rows):
        if lead >= cols:
            break
        # Find pivot
        i = r
        while M[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if lead == cols:
                    return M
        # Swap
        M.row_swap(r, i)
        # Eliminate below
        for i in range(r + 1, rows):
            if M[i, lead] != 0:
                factor = M[i, lead] / M[r, lead]
                M.row_op(i, lambda v, j: v - factor * M[r, j])
        lead += 1
    return M


sp.pprint(N)
# Apply
ref_manual = to_ref_sympy(N)

print("\nTrue Row Echelon Form (REF only):")
sp.pprint(ref_manual)

⎡1  2   -1  6 ⎤
⎢             ⎥
⎢3  8   9   10⎥
⎢             ⎥
⎣2  -1  2   -2⎦

True Row Echelon Form (REF only):
⎡1  2  -1   6 ⎤
⎢             ⎥
⎢0  2  12  -8 ⎥
⎢             ⎥
⎣0  0  34  -34⎦


In [ ]:
# 1.14 Transform to row echelon form RREF with sympy
O = sp.Matrix([[2,1,0,5],
                 [3,6,1,1],
                 [5,7,1,8]])
                 
to_row_echelon_form_sympy(O, show_steps=True)

Original Matrix:
⎡1  2   -1  6 ⎤
⎢             ⎥
⎢3  8   9   10⎥
⎢             ⎥
⎣2  -1  2   -2⎦

Row Echelon Form (RREF):
⎡1  0  0  1 ⎤
⎢           ⎥
⎢0  1  0  2 ⎥
⎢           ⎥
⎣0  0  1  -1⎦

Pivot columns: (0, 1, 2)


(Matrix([
 [1, 0, 0,  1],
 [0, 1, 0,  2],
 [0, 0, 1, -1]]),
 (0, 1, 2))

In [ ]:
# Transform to row echelon form REF with sympy
print("Original Matrix:")
sp.pprint(O)

ref_manual = to_ref_sympy(O)

print("\nTrue Row Echelon Form (REF only):")
sp.pprint(ref_manual)

Original Matrix:
⎡2  1  0  5⎤
⎢          ⎥
⎢3  6  1  1⎥
⎢          ⎥
⎣5  7  1  8⎦

True Row Echelon Form (REF only):
⎡2   1   0    5  ⎤
⎢                ⎥
⎢0  9/2  1  -13/2⎥
⎢                ⎥
⎣0   0   0    2  ⎦
